name: Build Release debian package
run-name: Build Release debian package
on:
  push:
    tags: [ 'v*' ]

jobs:
  builddeb:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install -y git-buildpackage debhelper build-essential
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - run: git tag
      - run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          gbp buildpackage --git-ignore-branch --git-upstream-version=$VERSION --git-upstream-tag='v%(version)s'
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          #body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Push Git Tag
        run: |
          git push origin --tags
      - name: upload debian package
        run: gh release upload ${{ github.ref_name }} ../*.deb
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

