name: Build Release RPM package
run-name: Build Release RPM package
on:
  push:
    tags: [ 'v*' ]

jobs:
  buildrpm:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y rpm
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - run: git tag
      - name: Set up RPM build environment
        run: |
          mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          cp tenstorrent-tools.spec ~/rpmbuild/SPECS/
          cp dev-hugepages\\x2d1G.mount hugepages-setup.sh tenstorrent-hugepages.service \
            ~/rpmbuild/SOURCES  
          ln -sf ~/rpmbuild/SOURCES/"dev-hugepages\x2d1G.mount" ~/rpmbuild/SOURCES/tt-hugepages-mount
          echo "%_unitdir /usr/lib/systemd/system" > ~/.rpmmacros
          version=$(echo ${{ github.ref_name }} | sed 's/^v//')
          sed -i "s/Version:.*/Version:        ${version}/" ~/rpmbuild/SPECS/tenstorrent-tools.spec
      - name: Build RPM package
        run: |
          rpmbuild -bb ~/rpmbuild/SPECS/tenstorrent-tools.spec
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Push Git Tag
        run: |
          git push origin --tags
      - name: upload RPM package
        run: |
          gh release upload ${{ github.ref_name }} ~/rpmbuild/RPMS/noarch/tenstorrent-tools-*.rpm
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
